---
- include: setup.yml
- include: config.yml
- include: filters.yml
- include: ssl.yml
- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
